Your user’s .npmrc file (${HOME}/.npmrc)
has a `globalconfig` and/or a `prefix` setting, which are incompatible with nvm.
Run `nvm use --delete-prefix v24.15.0 --silent` to unset it.
Your user’s .npmrc file (${HOME}/.npmrc)
has a `globalconfig` and/or a `prefix` setting, which are incompatible with nvm.
Run `nvm use --delete-prefix v24.15.0 --silent` to unset it.
Your user’s .npmrc file (${HOME}/.npmrc)
has a `globalconfig` and/or a `prefix` setting, which are incompatible with nvm.
Run `nvm use --delete-prefix v24.15.0 --silent` to unset it.
"""Liquid Ge radial distribution function via LAMMPS NVT MD.

Simple single-stage protocol:
  1. NVT equilibration at the liquid temperature (final snapshot is liquid)

Starting from diamond-cubic Ge at the specified lattice constant.
The NVT thermostat allows the system to melt and equilibrate.

Usage:
    python tests/liquid_rdf/liquid_rdf.py --pot results/potentials/pot.almtp
    python tests/liquid_rdf/liquid_rdf.py --pot results/potentials/pot.almtp \\
        --nx 4 --ny 4 --nz 4 --T 1500 --steps 10000 --outdir results/rdf_output
"""

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np

# Ensure the parent tests/ directory is on sys.path for utils imports
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from utils import compute_rdf, coordination_number, load_ref_rdf, read_lammps_dump

LAMMPS_DEFAULT = "lmp_mpi"
_GE_MASS_AMU = 72.630


# ---------------------------------------------------------------------------
# LAMMPS input writer
# ---------------------------------------------------------------------------

def write_liquid_input(
    workdir: Path,
    pot_path: str,
    nx: int = 4,
    ny: int = 4,
    nz: int = 4,
    a0: float = 5.658,
    T: float = 1500.0,
    steps: int = 10000,
    seed: int = 12345,
    dump_every: int = 100,
) -> int:
    """Write LAMMPS input for liquid Ge NVT equilibration.

    Returns the number of atoms in the supercell (8 * nx * ny * nz for
    the diamond-cubic conventional cell with 8 atoms).
    """
    n_atoms = 8 * nx * ny * nz

    lammps_in = f"""# Liquid Ge NVT MD — generated by liquid_rdf.py
units       metal
boundary    p p p
atom_style  atomic

# Diamond-cubic supercell: nx={nx} ny={ny} nz={nz}, a0={a0}
lattice     diamond {a0}
region      box block 0 {nx} 0 {ny} 0 {nz} units lattice
create_box  1 box
create_atoms 1 box
mass        1 {_GE_MASS_AMU}

pair_style  mlip load_from={pot_path} select=FALSE
pair_coeff  * *

neighbor    2.0 bin
neigh_modify delay 0 every 1 check yes
timestep    0.001   # ps
thermo      100
thermo_style custom step time temp press vol etotal

# ── NVT equilibration at {T:.0f} K ──
velocity    all create {T} {seed} mom yes rot yes
fix         nvt all nvt temp {T} {T} 0.1
dump        dmp all custom {dump_every} dump.lammpstrj id type x y z
dump_modify dmp sort id
run         {steps}
unfix       nvt

write_data  final.lammps
"""
    tmp = tempfile.NamedTemporaryFile(mode='w', dir='/tmp', delete=False, suffix='.liquid')
    try:
        tmp.write(lammps_in)
    finally:
        tmp.close()
    shutil.move(tmp.name, workdir / "in.liquid")
    return n_atoms


# ---------------------------------------------------------------------------
# RDF from dump (uses shared utils)
# ---------------------------------------------------------------------------

def compute_rdf_from_dump(
    dump_path: Path,
    n_atoms: int,
    rmax: float = 8.0,
    nbins: int = 200,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Read LAMMPS dump, compute and average g(r) over all frames.

    Returns (r, g_r, cells) where cells is an array of per-frame box matrices.
    """
    frames = read_lammps_dump(dump_path, n_atoms)
    if not frames:
        raise RuntimeError(f"No frames read from {dump_path}")

    print(f"  Using {len(frames)} frames for RDF averaging")
    g_total = np.zeros(nbins)
    r = None
    cells = []
    for cell_frame, pos in frames:
        r, g = compute_rdf(pos, cell_frame, rmax=rmax, nbins=nbins)
        g_total += g
        cells.append(cell_frame)

    return r, g_total / len(frames), np.array(cells)


# ---------------------------------------------------------------------------
# Main workflow
# ---------------------------------------------------------------------------

def run(
    pot: str,
    outdir: Path,
    lammps: str,
    np_cores: int,
    nx: int,
    ny: int,
    nz: int,
    a0: float,
    T: float,
    steps: int,
    rmax: float,
    nbins: int,
    ref_path: str | None = None,
) -> None:
    """Execute the full liquid RDF workflow.

    Steps:
        1. Write LAMMPS input file
        2. Run LAMMPS MD simulation
        3. Parse dump, compute g(r)
        4. Plot and save RDF figure + data file
    """
    outdir.mkdir(parents=True, exist_ok=True)

    n_atoms = 8 * nx * ny * nz
    total_time_ps = steps * 0.001

    print(f"  Liquid Ge at {T:.0f} K  |  {n_atoms} atoms  "
          f"({nx}×{ny}×{nz} diamond cells, a0={a0} Å)")
    print(f"  Protocol: {steps:,} NVT steps ({total_time_ps:.1f} ps)")

    workdir = outdir / "lammps_run"
    workdir.mkdir(exist_ok=True)

    pot_abs = str(Path(pot).resolve())
    dump_every = max(10, steps // 200)

    n_atoms_written = write_liquid_input(
        workdir, pot_abs,
        nx=nx, ny=ny, nz=nz, a0=a0,
        T=T, steps=steps,
        dump_every=dump_every,
    )
    assert n_atoms_written == n_atoms

    # ── Run LAMMPS ──
    print("  Running LAMMPS ...")
    lmp_cmd = [lammps, "-in", "in.liquid", "-log", "liquid.log"]
    if np_cores > 1:
        lmp_cmd = ["mpirun", "-np", str(np_cores)] + lmp_cmd
    result = subprocess.run(
        lmp_cmd, cwd=workdir, capture_output=True, text=True
    )
    if result.returncode != 0:
        print("  LAMMPS stderr (last 500 chars):")
        print(result.stderr[-500:])
        raise RuntimeError("LAMMPS run failed")

    dump = workdir / "dump.lammpstrj"
    if not dump.exists():
        raise RuntimeError(f"LAMMPS dump not found at {dump}")

    # ── Compute RDF ──
    print("  Computing RDF ...")
    r, g_r, cells = compute_rdf_from_dump(dump, n_atoms, rmax=rmax, nbins=nbins)

    # Density from the actual simulation box (mean over collected frames)
    vols = np.array([abs(np.linalg.det(c)) for c in cells])
    L_mean = vols.mean() ** (1.0 / 3.0)
    rho = n_atoms / vols.mean()
    density_gcm3 = rho * _GE_MASS_AMU / 0.6022

    cn = coordination_number(r, g_r, rho)
    mask_first = r < 3.5
    if np.any(mask_first):
        i_peak = int(np.argmax(g_r[mask_first]))
        r_peak = r[mask_first][i_peak]
        g_peak = g_r[mask_first][i_peak]
    else:
        i_peak = int(np.argmax(g_r))
        r_peak = r[i_peak]
        g_peak = g_r[i_peak]

    print(f"  1st peak at r = {r_peak:.3f} Å,  g(r_peak) = {g_peak:.2f}")
    print(f"  Coordination number (r < 3.5 Å): {cn:.2f}  [expected: 6–9]")
    print(f"  Simulation density: {density_gcm3:.3f} g/cm³")

    # ── Save RDF data ──
    txt = outdir / "liquid_rdf.txt"
    tmp_txt = tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False, dir="/tmp")
    try:
        tmp_txt.write(f"# Liquid Ge RDF at {T:.0f} K  |  pot: {pot}\n")
        tmp_txt.write(f"# density = {density_gcm3:.3f} g/cm³\n")
        tmp_txt.write(f"# 1st peak at r = {r_peak:.3f} Å   CN = {cn:.2f}\n")
        tmp_txt.write("# r[A]  g(r)\n")
        for ri, gi in zip(r, g_r):
            tmp_txt.write(f"  {ri:.4f}  {gi:.6f}\n")
        tmp_txt.close()
        shutil.move(tmp_txt.name, txt)
    finally:
        if not tmp_txt.closed:
            tmp_txt.close()
    print(f"  Data written to {txt}")

    # ── Plot ──
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(8, 5))
        ax.plot(r, g_r, color="tab:purple", lw=1.5, label="MTP")
        ax.axhline(1.0, color="gray", lw=0.8, ls="--")

        # Overlay reference if provided
        r_ref, g_ref = load_ref_rdf(ref_path)
        if r_ref is not None:
            ax.plot(r_ref, g_ref, color="tab:orange", lw=1.0, ls="--",
                    alpha=0.9, label="ref")

        ax.axvline(r_peak, color="tab:red", lw=0.8, ls=":",
                   label=f"1st peak: {r_peak:.2f} Å")
        ax.set_xlabel("r (Å)", fontsize=12)
        ax.set_ylabel("g(r)", fontsize=12)
        ax.set_title(
            f"Liquid Ge g(r) at {T:.0f} K  "
            f"[ρ = {density_gcm3:.2f} g/cm³]",
            fontsize=13,
        )
        ax.legend(fontsize=10)
        ax.set_xlim(0, rmax)
        fig.tight_layout()
        png = outdir / "liquid_rdf.png"
        tmp_png = tempfile.NamedTemporaryFile(suffix=".png", delete=False, dir="/tmp")
        tmp_png.close()
        fig.savefig(tmp_png.name, dpi=150)
        shutil.move(tmp_png.name, png)
        plt.close(fig)
        print(f"  Plot saved to {png}")
    except ImportError as e:
        print(f"  Matplotlib not available ({e}); skipping plot.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Liquid Ge RDF test via LAMMPS NVT MD"
    )
    parser.add_argument(
        "--pot", required=True,
        help="Path to MTP potential file (.almtp)"
    )
    parser.add_argument(
        "--nx", type=int, default=4,
        help="Number of unit cells in x direction (default: 4)"
    )
    parser.add_argument(
        "--ny", type=int, default=4,
        help="Number of unit cells in y direction (default: 4)"
    )
    parser.add_argument(
        "--nz", type=int, default=4,
        help="Number of unit cells in z direction (default: 4)"
    )
    parser.add_argument(
        "--a0", type=float, default=5.658,
        help="Lattice constant for diamond-cubic Ge in Å (default: 5.658)"
    )
    parser.add_argument(
        "--T", type=float, default=1500.0,
        help="Liquid temperature in K (default: 1500)"
    )
    parser.add_argument(
        "--steps", type=int, default=10000,
        help="Equilibration steps (default: 10000 = 10 ps)"
    )
    parser.add_argument(
        "--lammps", default=LAMMPS_DEFAULT,
        help="LAMMPS binary path (default: lmp_mpi)"
    )
    parser.add_argument(
        "--np", type=int, default=1,
        help="MPI processes (default: 1; wraps with mpirun if >1)"
    )
    parser.add_argument(
        "--outdir", default="results/tests/liquid_rdf",
        help="Output directory (default: results/tests/liquid_rdf)"
    )
    parser.add_argument(
        "--rmax", type=float, default=8.0,
        help="Max r for g(r) in Å (default: 8.0)"
    )
    parser.add_argument(
        "--nbins", type=int, default=200,
        help="Number of RDF bins (default: 200)"
    )
    parser.add_argument(
        "--ref", default=None,
        help="Optional path to reference RDF data file for overlay"
    )
    args = parser.parse_args()

    run(
        pot=args.pot,
        outdir=Path(args.outdir),
        lammps=args.lammps,
        np_cores=args.np,
        nx=args.nx,
        ny=args.ny,
        nz=args.nz,
        a0=args.a0,
        T=args.T,
        steps=args.steps,
        rmax=args.rmax,
        nbins=args.nbins,
        ref_path=args.ref,
    )


if __name__ == "__main__":
    main()
