"""Melt-quench amorphous Ge RDF via LAMMPS.

Three-stage protocol:
  1. NVT at 300 K  (5 ps  — equilibrate diamond)
  2. NVT at T_melt (20 ps — melt)
  3. NPT quench T_melt → 300 K at rate --quench-rate K/s
  4. NVT at 300 K  (5 ps  — equilibrate amorphous)

Reference a-Ge RDF: 1st peak ≈ 2.5 Å, no long-range order.

Usage:
    # Quick test (10× faster quench, interactive):
    python tests/amorphous_rdf.py --pot results/potentials/pot_al.almtp --quick

    # Full production run (submit via SLURM):
    sbatch scripts/submit_active_learning.sh  # or write a dedicated submit script
    python tests/amorphous_rdf.py --pot results/potentials/pot_al.almtp \\
        --T-melt 1800 --quench-rate 1e12
"""

import argparse
import subprocess
import sys
from pathlib import Path

import numpy as np

LAMMPS_DEFAULT = "lmp_mpi"
_GE_LIQUID_DENSITY_GCM3 = 5.60  # a-Ge density ≈ 5.35 g/cm³; use melt density for box
_GE_MASS_AMU = 72.630


# ---------------------------------------------------------------------------
# LAMMPS input writer
# ---------------------------------------------------------------------------

def _quench_steps(T_high: float, T_low: float, rate_K_per_s: float,
                  timestep_ps: float = 0.001) -> int:
    """Compute number of MD steps for a given temperature ramp."""
    delta_T = T_high - T_low
    time_ps = delta_T / rate_K_per_s * 1e12  # seconds → picoseconds
    return max(1000, int(time_ps / timestep_ps))


def write_amorphous_input(
    workdir: Path,
    pot_path: str,
    n_cells: int = 3,
    T_melt: float = 1800.0,
    quench_rate: float = 1e12,
    steps_eq_diamond: int = 5_000,
    steps_melt: int = 20_000,
    steps_eq_amor: int = 5_000,
    seed: int = 99999,
    dump_every: int = 200,
) -> int:
    """Write LAMMPS input; returns number of quench steps."""
    a0 = 5.658
    n_atoms = 8 * n_cells ** 3

    # Box size from diamond lattice (scale slightly for melt)
    L0 = n_cells * a0
    scale = (_GE_LIQUID_DENSITY_GCM3 * (n_cells * a0) ** 3 /
             (n_atoms * _GE_MASS_AMU / 6.02214076e23 * 1e24) *
             (n_atoms * _GE_MASS_AMU / 6.02214076e23 * 1e24) /
             (_GE_LIQUID_DENSITY_GCM3 * (n_cells * a0) ** 3)) ** (1.0 / 3.0)
    # Simpler: keep diamond box for initial structure, let NPT relax volume
    L = L0

    n_quench = _quench_steps(T_melt, 300.0, quench_rate)

    lammps_in = f"""# Melt-quench amorphous Ge — generated by amorphous_rdf.py
units       metal
boundary    p p p
atom_style  atomic

lattice     diamond {a0}
region      box block 0 {n_cells} 0 {n_cells} 0 {n_cells} units lattice
create_box  1 box
create_atoms 1 box
mass        1 {_GE_MASS_AMU}

pair_style  mlip load_from={pot_path} select=FALSE
pair_coeff  * *

neighbor    2.0 bin
neigh_modify delay 0 every 1 check yes
timestep    0.001
thermo      1000
thermo_style custom step time temp press vol etotal

# ── Stage 1: equilibrate diamond at 300 K ──
velocity    all create 300 {seed} mom yes rot yes
fix         nvt1 all nvt temp 300 300 0.1
run         {steps_eq_diamond}
unfix       nvt1

# ── Stage 2: heat to {T_melt:.0f} K and melt ──
fix         nvt2 all nvt temp 300 {T_melt} 0.5
run         5000
unfix       nvt2
fix         nvt3 all nvt temp {T_melt} {T_melt} 0.1
run         {steps_melt}
unfix       nvt3

# ── Stage 3: NPT quench {T_melt:.0f} K → 300 K at {quench_rate:.0e} K/s ──
fix         npt1 all npt temp {T_melt} 300 0.1 iso 0 0 1.0
run         {n_quench}
unfix       npt1

# ── Stage 4: equilibrate amorphous at 300 K ──
fix         nvt4 all nvt temp 300 300 0.1
dump        dmp all custom {dump_every} dump_amor.lammpstrj id type x y z
dump_modify dmp sort id
run         {steps_eq_amor}
unfix       nvt4

write_data  amorphous.lammps
"""
    (workdir / "in.amorphous").write_text(lammps_in)
    return n_quench


# ---------------------------------------------------------------------------
# RDF (reused from liquid_rdf)
# ---------------------------------------------------------------------------

def compute_rdf(positions: np.ndarray, cell: np.ndarray,
                rmax: float = 8.0, nbins: int = 200) -> tuple[np.ndarray, np.ndarray]:
    N = len(positions)
    dr = rmax / nbins
    cell_inv = np.linalg.inv(cell)
    diff = positions[:, None, :] - positions[None, :, :]
    frac = diff @ cell_inv
    frac -= np.round(frac)
    diff_mic = frac @ cell
    dists = np.linalg.norm(diff_mic, axis=-1)
    np.fill_diagonal(dists, rmax + 1.0)
    flat = dists.flatten()
    flat = flat[flat < rmax]
    hist, _ = np.histogram(flat, bins=nbins, range=(0.0, rmax))
    r = np.linspace(dr / 2.0, rmax - dr / 2.0, nbins)
    volume = abs(np.linalg.det(cell))
    rho = N / volume
    shell_vol = (4.0 / 3.0) * np.pi * ((r + dr / 2.0) ** 3 - (r - dr / 2.0) ** 3)
    g_r = hist / (N * rho * shell_vol)
    return r, g_r


def _read_lammps_dump(path: Path, n_atoms: int) -> list[tuple[np.ndarray, np.ndarray]]:
    """Return list of (cell, positions) tuples from a LAMMPS custom dump."""
    frames = []
    text = path.read_text()
    blocks = text.split("ITEM: TIMESTEP")
    for block in blocks[1:]:
        lines = block.splitlines()
        # Box bounds
        try:
            box_line = next(i for i, l in enumerate(lines) if "ITEM: BOX BOUNDS" in l)
            lx = float(lines[box_line + 1].split()[1]) - float(lines[box_line + 1].split()[0])
            ly = float(lines[box_line + 2].split()[1]) - float(lines[box_line + 2].split()[0])
            lz = float(lines[box_line + 3].split()[1]) - float(lines[box_line + 3].split()[0])
            cell = np.diag([lx, ly, lz])
        except (StopIteration, IndexError, ValueError):
            cell = None

        try:
            atom_line = next(i for i, l in enumerate(lines) if "ITEM: ATOMS" in l)
        except StopIteration:
            continue

        pos = []
        for line in lines[atom_line + 1: atom_line + 1 + n_atoms]:
            parts = line.split()
            if len(parts) >= 5:
                pos.append([float(parts[2]), float(parts[3]), float(parts[4])])
        if len(pos) == n_atoms and cell is not None:
            frames.append((cell, np.array(pos)))
    return frames


# ---------------------------------------------------------------------------
# Main workflow
# ---------------------------------------------------------------------------

def run(
    pot: str,
    outdir: Path,
    lammps: str,
    n_cells: int,
    T_melt: float,
    quench_rate: float,
    rmax: float,
    nbins: int,
) -> None:
    outdir.mkdir(parents=True, exist_ok=True)

    n_atoms = 8 * n_cells ** 3
    n_quench = _quench_steps(T_melt, 300.0, quench_rate)
    total_steps = 5000 + 5000 + 20_000 + n_quench + 5000

    print(f"  Amorphous Ge  |  {n_atoms} atoms  |  T_melt = {T_melt:.0f} K")
    print(f"  Quench rate = {quench_rate:.0e} K/s  →  {n_quench:,} quench steps")
    print(f"  Total steps ≈ {total_steps:,}  (~{total_steps * 0.001 / 1000:.1f} ns)")

    if n_quench > 500_000 and sys.stdout.isatty():
        print("\n  *** NOTE: This is a long run (>500 k steps). ***")
        print("  Consider submitting via SLURM:")
        print(f"    sbatch scripts/submit_amorphous_rdf.sh {pot}")
        print("  Or use --quick for a 10× faster quench (10^13 K/s).\n")

    workdir = outdir / "lammps_run"
    workdir.mkdir(exist_ok=True)

    pot_abs = str(Path(pot).resolve())
    n_quench = write_amorphous_input(
        workdir, pot_abs,
        n_cells=n_cells,
        T_melt=T_melt,
        quench_rate=quench_rate,
    )

    print("  Running LAMMPS ...")
    lmp_cmd = [lammps, "-in", "in.amorphous", "-log", "amorphous.log"]
    result = subprocess.run(lmp_cmd, cwd=workdir, capture_output=True, text=True)
    if result.returncode != 0:
        print("  LAMMPS stderr (last 500 chars):")
        print(result.stderr[-500:])
        raise RuntimeError("LAMMPS run failed")

    dump = workdir / "dump_amor.lammpstrj"
    if not dump.exists():
        raise RuntimeError(f"LAMMPS dump not found at {dump}")

    print("  Reading dump and computing RDF ...")
    frames = _read_lammps_dump(dump, n_atoms)
    if not frames:
        raise RuntimeError("No frames read from dump file")

    print(f"  {len(frames)} frames available; using all for RDF averaging")
    g_total = np.zeros(nbins)
    r = None
    for cell_frame, pos in frames:
        r, g = compute_rdf(pos, cell_frame, rmax=rmax, nbins=nbins)
        g_total += g
    g_r = g_total / len(frames)

    i_peak = int(np.argmax(g_r[r < 3.0]))
    r_peak = r[i_peak]
    print(f"  1st peak at r = {r_peak:.3f} Å  [expected ≈ 2.5 Å for a-Ge]")

    txt = outdir / "amorphous_rdf.txt"
    with open(txt, "w") as f:
        f.write(f"# Amorphous Ge RDF  |  pot: {pot}\n")
        f.write(f"# T_melt = {T_melt:.0f} K  quench_rate = {quench_rate:.0e} K/s\n")
        f.write(f"# 1st peak at r = {r_peak:.3f} Å\n")
        f.write("# r[A]  g(r)\n")
        for ri, gi in zip(r, g_r):
            f.write(f"  {ri:.4f}  {gi:.6f}\n")
    print(f"  Data written to {txt}")

    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(8, 5))
        ax.plot(r, g_r, color="tab:purple", lw=1.5)
        ax.axhline(1.0, color="gray", lw=0.8, ls="--")
        ax.axvline(r_peak, color="tab:red", lw=0.8, ls=":", label=f"1st peak: {r_peak:.2f} Å")
        ax.set_xlabel("r (Å)", fontsize=12)
        ax.set_ylabel("g(r)", fontsize=12)
        ax.set_title(
            f"Amorphous Ge g(r)  [quench {quench_rate:.0e} K/s] — MTP", fontsize=13
        )
        ax.legend(fontsize=10)
        ax.set_xlim(0, rmax)
        fig.tight_layout()
        png = outdir / "amorphous_rdf.png"
        fig.savefig(png, dpi=150)
        plt.close(fig)
        print(f"  Plot saved to {png}")
    except ImportError as e:
        print(f"  Matplotlib not available ({e}); skipping plot.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Melt-quench amorphous Ge RDF via LAMMPS"
    )
    parser.add_argument("--pot", required=True, help="Path to potential (.almtp)")
    parser.add_argument("--T-melt", type=float, default=1800.0,
                        help="Melt temperature in K (default: 1800)")
    parser.add_argument("--quench-rate", type=float, default=1e12,
                        help="Quench rate in K/s (default: 1e12; use 1e13 for --quick)")
    parser.add_argument("--quick", action="store_true",
                        help="Use 1e13 K/s quench rate for a quick validation run")
    parser.add_argument("--n-cells", type=int, default=3,
                        help="Supercell repeat (8·n³ atoms, default: 3→216)")
    parser.add_argument("--rmax", type=float, default=8.0)
    parser.add_argument("--nbins", type=int, default=200)
    parser.add_argument("--outdir", default="results/tests/amorphous_rdf")
    parser.add_argument("--lammps", default=LAMMPS_DEFAULT)
    args = parser.parse_args()

    quench_rate = 1e13 if args.quick else args.quench_rate

    run(
        pot=args.pot,
        outdir=Path(args.outdir),
        lammps=args.lammps,
        n_cells=args.n_cells,
        T_melt=args.T_melt,
        quench_rate=quench_rate,
        rmax=args.rmax,
        nbins=args.nbins,
    )


if __name__ == "__main__":
    main()
