"""Liquid Ge radial distribution function at 1300 K.

Runs LAMMPS NVT MD, reads the dump file, and computes g(r).

Reference: first peak at ~2.6 Å, coordination number ≈ 6–9.

Usage:
    python tests/liquid_rdf.py --pot results/potentials/pot_al.almtp
    python tests/liquid_rdf.py --pot results/potentials/pot_al.almtp \\
        --T 1300 --steps-eq 20000 --outdir results/tests/liquid_rdf
"""

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np

MLP_DEFAULT = "/scratch/project_2012355/Paper_3/mlip-3-prune/bin/mlp"
LAMMPS_DEFAULT = "lmp_mpi"

# Liquid Ge density at 1300 K ≈ 5.50 g/cm³  (Waseda 1980)
_GE_LIQUID_DENSITY_GCM3 = 5.50
_GE_MASS_AMU = 72.630


# ---------------------------------------------------------------------------
# LAMMPS input writer
# ---------------------------------------------------------------------------

def write_liquid_input(
    workdir: Path,
    pot_path: str,
    n_cells: int = 3,        # creates n_cells³ diamond supercell
    T: float = 1300.0,
    steps_heat: int = 10_000,
    steps_eq: int = 20_000,
    seed: int = 12345,
    dump_every: int = 100,
) -> None:
    """Write LAMMPS input for liquid Ge NVT MD."""
    a0_diamond = 5.658
    n_atoms = 8 * n_cells ** 3

    # Target box size for liquid density
    mass_g = n_atoms * _GE_MASS_AMU / 6.02214076e23
    vol_cm3 = mass_g / _GE_LIQUID_DENSITY_GCM3
    l_angstrom = (vol_cm3 * 1e24) ** (1.0 / 3.0)
    scale = l_angstrom / (n_cells * a0_diamond)

    lammps_in = f"""# Liquid Ge NVT MD — generated by liquid_rdf.py
units       metal
boundary    p p p
atom_style  atomic

lattice     diamond {a0_diamond}
region      box block 0 {n_cells} 0 {n_cells} 0 {n_cells} units lattice
create_box  1 box
create_atoms 1 box
mass        1 {_GE_MASS_AMU}

# Scale box to target liquid density ({_GE_LIQUID_DENSITY_GCM3} g/cm³)
change_box  all x scale {scale:.6f} y scale {scale:.6f} z scale {scale:.6f} remap

pair_style  mlip load_from={pot_path} select=FALSE
pair_coeff  * *

neighbor    2.0 bin
neigh_modify delay 0 every 1 check yes

# ── Stage 1: heat 300 K → {T:.0f} K ──
velocity    all create 300 {seed} mom yes rot yes
fix         heat all nvt temp 300 {T} 0.1
timestep    0.001
thermo      1000
thermo_style custom step time temp press vol etotal
run         {steps_heat}
unfix       heat

# ── Stage 2: equilibrate at {T:.0f} K ──
fix         nvt_eq all nvt temp {T} {T} 0.1
thermo      1000
thermo_style custom step time temp press vol etotal
dump        dmp all custom {dump_every} dump.lammpstrj id type x y z
dump_modify dmp sort id
run         {steps_eq}
unfix       nvt_eq

write_data  final.lammps
"""
    (workdir / "in.liquid").write_text(lammps_in)


# ---------------------------------------------------------------------------
# RDF computation
# ---------------------------------------------------------------------------

def compute_rdf(positions: np.ndarray, cell: np.ndarray,
                rmax: float = 8.0, nbins: int = 200) -> tuple[np.ndarray, np.ndarray]:
    """Compute g(r) for a single frame using vectorised minimum-image distances."""
    N = len(positions)
    dr = rmax / nbins
    cell_inv = np.linalg.inv(cell)

    diff = positions[:, None, :] - positions[None, :, :]  # (N,N,3)
    frac = diff @ cell_inv
    frac -= np.round(frac)
    diff_mic = frac @ cell
    dists = np.linalg.norm(diff_mic, axis=-1)  # (N,N)
    np.fill_diagonal(dists, rmax + 1.0)

    flat = dists.flatten()
    flat = flat[flat < rmax]
    hist, _ = np.histogram(flat, bins=nbins, range=(0.0, rmax))

    r = np.linspace(dr / 2.0, rmax - dr / 2.0, nbins)
    volume = abs(np.linalg.det(cell))
    rho = N / volume
    shell_vol = (4.0 / 3.0) * np.pi * ((r + dr / 2.0) ** 3 - (r - dr / 2.0) ** 3)
    g_r = hist / (N * rho * shell_vol)
    return r, g_r


def compute_rdf_from_dump(
    dump_path: Path,
    cell: np.ndarray,
    n_atoms: int,
    rmax: float = 8.0,
    nbins: int = 200,
    skip_frames: int = 50,
) -> tuple[np.ndarray, np.ndarray]:
    """Read LAMMPS dump, compute and average g(r) over the last frames."""
    frames = _read_lammps_dump(dump_path, n_atoms)
    if not frames:
        raise RuntimeError(f"No frames read from {dump_path}")

    frames_to_use = frames[skip_frames:]
    if not frames_to_use:
        frames_to_use = frames

    print(f"  Using {len(frames_to_use)} frames for RDF averaging")
    g_total = np.zeros(nbins)
    for pos in frames_to_use:
        _, g = compute_rdf(pos, cell, rmax=rmax, nbins=nbins)
        g_total += g

    r = np.linspace(rmax / (2 * nbins), rmax - rmax / (2 * nbins), nbins)
    return r, g_total / len(frames_to_use)


def _read_lammps_dump(path: Path, n_atoms: int) -> list[np.ndarray]:
    """Parse LAMMPS custom dump (id type x y z) → list of position arrays."""
    frames = []
    text = path.read_text()
    blocks = text.split("ITEM: TIMESTEP")
    for block in blocks[1:]:
        lines = block.splitlines()
        # Find "ITEM: ATOMS" line
        try:
            atom_line = next(i for i, l in enumerate(lines) if "ITEM: ATOMS" in l)
        except StopIteration:
            continue
        pos = []
        for line in lines[atom_line + 1: atom_line + 1 + n_atoms]:
            parts = line.split()
            if len(parts) >= 5:
                # format: id type x y z
                pos.append([float(parts[2]), float(parts[3]), float(parts[4])])
        if len(pos) == n_atoms:
            frames.append(np.array(pos))
    return frames


# ---------------------------------------------------------------------------
# Coordination number
# ---------------------------------------------------------------------------

def coordination_number(r: np.ndarray, g_r: np.ndarray,
                        rho: float, r_cutoff: float = 3.5) -> float:
    """Integrate g(r) to get CN up to r_cutoff."""
    mask = r <= r_cutoff
    dr = r[1] - r[0]
    return float(4.0 * np.pi * rho * np.trapz(g_r[mask] * r[mask] ** 2, r[mask]))


# ---------------------------------------------------------------------------
# Main workflow
# ---------------------------------------------------------------------------

def run(
    pot: str,
    outdir: Path,
    lammps: str,
    n_cells: int,
    T: float,
    steps_eq: int,
    rmax: float,
    nbins: int,
) -> None:
    outdir.mkdir(parents=True, exist_ok=True)

    n_atoms = 8 * n_cells ** 3
    a0_diamond = 5.658

    # Compute actual box length after density scaling
    mass_g = n_atoms * _GE_MASS_AMU / 6.02214076e23
    vol_cm3 = mass_g / _GE_LIQUID_DENSITY_GCM3
    L = (vol_cm3 * 1e24) ** (1.0 / 3.0)
    cell = np.diag([L, L, L])
    rho = n_atoms / L ** 3

    print(f"  Liquid Ge at {T:.0f} K  |  {n_atoms} atoms  |  L = {L:.3f} Å")
    print(f"  ρ = {rho * _GE_MASS_AMU / 0.6022:.3f} g/cm³  (target {_GE_LIQUID_DENSITY_GCM3})")

    workdir = outdir / "lammps_run"
    workdir.mkdir(exist_ok=True)

    pot_abs = str(Path(pot).resolve())
    write_liquid_input(
        workdir, pot_abs,
        n_cells=n_cells, T=T,
        steps_heat=max(5000, steps_eq // 4),
        steps_eq=steps_eq,
        dump_every=max(10, steps_eq // 200),
    )

    print(f"  Running LAMMPS ({steps_eq} equilibration steps) ...")
    lmp_cmd = [lammps, "-in", "in.liquid", "-log", "liquid.log"]
    result = subprocess.run(
        lmp_cmd, cwd=workdir, capture_output=True, text=True
    )
    if result.returncode != 0:
        print("  LAMMPS stderr (last 500 chars):")
        print(result.stderr[-500:])
        raise RuntimeError("LAMMPS run failed")

    dump = workdir / "dump.lammpstrj"
    if not dump.exists():
        raise RuntimeError(f"LAMMPS dump not found at {dump}")

    print("  Computing RDF ...")
    r, g_r = compute_rdf_from_dump(dump, cell, n_atoms, rmax=rmax, nbins=nbins)

    cn = coordination_number(r, g_r, rho)
    i_peak = int(np.argmax(g_r[r < 3.5]))
    r_peak = r[i_peak]
    print(f"  1st peak at r = {r_peak:.3f} Å,  g(r_peak) = {g_r[i_peak]:.2f}")
    print(f"  Coordination number (r < 3.5 Å): {cn:.2f}  [expected: 6–9]")

    # Write data
    txt = outdir / "liquid_rdf.txt"
    with open(txt, "w") as f:
        f.write(f"# Liquid Ge RDF at {T:.0f} K  |  pot: {pot}\n")
        f.write(f"# 1st peak at r = {r_peak:.3f} Å   CN = {cn:.2f}\n")
        f.write("# r[A]  g(r)\n")
        for ri, gi in zip(r, g_r):
            f.write(f"  {ri:.4f}  {gi:.6f}\n")
    print(f"  Data written to {txt}")

    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(8, 5))
        ax.plot(r, g_r, color="tab:blue", lw=1.5)
        ax.axhline(1.0, color="gray", lw=0.8, ls="--")
        ax.axvline(r_peak, color="tab:red", lw=0.8, ls=":", label=f"1st peak: {r_peak:.2f} Å")
        ax.set_xlabel("r (Å)", fontsize=12)
        ax.set_ylabel("g(r)", fontsize=12)
        ax.set_title(f"Liquid Ge g(r) at {T:.0f} K — MTP", fontsize=13)
        ax.legend(fontsize=10)
        ax.set_xlim(0, rmax)
        fig.tight_layout()
        png = outdir / "liquid_rdf.png"
        fig.savefig(png, dpi=150)
        plt.close(fig)
        print(f"  Plot saved to {png}")
    except ImportError as e:
        print(f"  Matplotlib not available ({e}); skipping plot.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Liquid Ge RDF test via LAMMPS NVT MD"
    )
    parser.add_argument("--pot", required=True, help="Path to potential (.almtp)")
    parser.add_argument("--T", type=float, default=1300.0,
                        help="Temperature in K (default: 1300)")
    parser.add_argument("--n-cells", type=int, default=3,
                        help="Supercell repeat (creates 8·n³ atoms, default: 3→216)")
    parser.add_argument("--steps-eq", type=int, default=20_000,
                        help="NVT equilibration steps (default: 20000)")
    parser.add_argument("--rmax", type=float, default=8.0,
                        help="Max r for g(r) in Å (default: 8.0)")
    parser.add_argument("--nbins", type=int, default=200,
                        help="Number of RDF bins (default: 200)")
    parser.add_argument("--outdir", default="results/tests/liquid_rdf")
    parser.add_argument("--lammps", default=LAMMPS_DEFAULT,
                        help="LAMMPS binary (default: lmp_mpi)")
    args = parser.parse_args()

    run(
        pot=args.pot,
        outdir=Path(args.outdir),
        lammps=args.lammps,
        n_cells=args.n_cells,
        T=args.T,
        steps_eq=args.steps_eq,
        rmax=args.rmax,
        nbins=args.nbins,
    )


if __name__ == "__main__":
    main()
