"""Melt-quench amorphous Ge RDF via LAMMPS.

Three-stage protocol:
  1. NVT at 300 K  (5 ps  — equilibrate diamond)
  2. NVT at T_melt (20 ps — melt)
  3. NPT quench T_melt → 300 K at rate --quench-rate K/s
  4. NVT at 300 K  (5 ps  — equilibrate amorphous)

Reference a-Ge RDF: 1st peak ≈ 2.5 Å, no long-range order.

Usage:
    # Quick test (10× faster quench, interactive):
    python src/physical_validation/amorphous_rdf.py --pot results/potentials/pot_al.almtp --quick

    # Full production run (consider submitting via SLURM for long quenches):
    python src/physical_validation/amorphous_rdf.py --pot results/potentials/pot_al.almtp \\
        --T-melt 1800 --quench-rate 1e12
"""

import argparse
import subprocess
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
sys.path.insert(0, str(Path(__file__).parent.parent / "utils"))
from utils import compute_rdf, coordination_number, load_ref_rdf, read_lammps_dump

LAMMPS_DEFAULT = "lmp_mpi"
_GE_MASS_AMU = 72.630


# ---------------------------------------------------------------------------
# LAMMPS input writer
# ---------------------------------------------------------------------------


def _quench_steps(T_high: float, T_low: float, rate_K_per_s: float,
                  timestep_ps: float = 0.001) -> int:
    """Compute number of MD steps for a given temperature ramp."""
    delta_T = T_high - T_low
    time_ps = delta_T / rate_K_per_s * 1e12  # seconds → picoseconds
    return max(1000, int(time_ps / timestep_ps))


def write_amorphous_input(
    workdir: Path,
    pot_path: str,
    n_cells: int = 3,
    T_melt: float = 1800.0,
    quench_rate: float = 1e12,
    steps_eq_diamond: int = 5_000,
    steps_melt: int = 20_000,
    steps_npt_eq: int = 100_000,
    steps_eq_amor: int = 5_000,
    seed: int = 99999,
    dump_every: int = 200,
) -> None:
    """Write LAMMPS input for melt-quench amorphous Ge."""
    a0 = 5.7567
    n_quench = _quench_steps(T_melt, 300.0, quench_rate)

    lammps_in = f"""# Melt-quench amorphous Ge — generated by amorphous_rdf.py
units       metal
boundary    p p p
atom_style  atomic

lattice     diamond {a0}
region      box block 0 {n_cells} 0 {n_cells} 0 {n_cells} units lattice
create_box  1 box
create_atoms 1 box
mass        1 {_GE_MASS_AMU}

pair_style  mlip load_from={pot_path} select=FALSE
pair_coeff  * *

neighbor    2.0 bin
neigh_modify delay 0 every 1 check yes
timestep    0.001
thermo      1000
thermo_style custom step time temp press vol etotal

# ── Stage 1: equilibrate diamond at 300 K ──
velocity    all create 300 {seed} mom yes rot yes
fix         nvt1 all nvt temp 300 300 0.1
run         {steps_eq_diamond}
unfix       nvt1

# ── Stage 2: heat to {T_melt:.0f} K and melt ──
fix         nvt2 all nvt temp 300 {T_melt} 0.5
run         5000
unfix       nvt2
fix         nvt3 all nvt temp {T_melt} {T_melt} 0.1
run         {steps_melt}
unfix       nvt3

# ── Stage 2b: NPT equilibrate melt at {T_melt:.0f} K (relax box to liquid volume) ──
# Use 10 ps barostat damping (10× longer than default) to avoid runaway expansion
# when starting from high NVT pressure (~24 kbar after melt).
fix         npt_melt all npt temp {T_melt} {T_melt} 0.1 iso 0 0 10.0
run         {steps_npt_eq}
unfix       npt_melt

# ── Stage 3: NPT quench {T_melt:.0f} K → 300 K ──
fix         npt1 all npt temp {T_melt} 300 0.1 iso 0 0 10.0
run         {n_quench}
unfix       npt1

# ── Stage 4: equilibrate amorphous at 300 K ──
fix         nvt4 all nvt temp 300 300 0.1
dump        dmp all custom {dump_every} dump_amor.lammpstrj id type x y z
dump_modify dmp sort id
run         {steps_eq_amor}
unfix       nvt4

write_data  amorphous.lammps
"""
    (workdir / "in.amorphous").write_text(lammps_in)


# ---------------------------------------------------------------------------
# Main workflow
# ---------------------------------------------------------------------------


def run(
    pot: str,
    outdir: Path,
    lammps: str,
    np_cores: int,
    n_cells: int,
    T_melt: float,
    quench_rate: float,
    rmax: float,
    nbins: int,
    ref_highbound: str | None = None,
    ref_lowbound: str | None = None,
) -> None:
    outdir.mkdir(parents=True, exist_ok=True)

    n_atoms = 8 * n_cells ** 3
    n_quench = _quench_steps(T_melt, 300.0, quench_rate)
    total_steps = 5_000 + 5_000 + 20_000 + 50_000 + n_quench + 5_000

    print(f"  Amorphous Ge  |  {n_atoms} atoms  |  T_melt = {T_melt:.0f} K")
    print(f"  Quench rate = {quench_rate:.0e} K/s  →  {n_quench:,} quench steps")
    print(f"  Total steps ≈ {total_steps:,}  (~{total_steps * 0.001 / 1000:.1f} ns)")

    if n_quench > 500_000 and sys.stdout.isatty():
        print("\n  *** NOTE: This is a long run (>500 k steps). ***")
        print("  Consider submitting via SLURM.")
        print("  Or use --quick for a 10× faster quench (10^13 K/s).\n")

    workdir = outdir / "lammps_run"
    workdir.mkdir(exist_ok=True)

    pot_abs = str(Path(pot).resolve())
    write_amorphous_input(
        workdir, pot_abs,
        n_cells=n_cells,
        T_melt=T_melt,
        quench_rate=quench_rate,
    )

    print("  Running LAMMPS ...")
    lmp_cmd = [lammps, "-in", "in.amorphous", "-log", "amorphous.log"]
    if np_cores > 1:
        lmp_cmd = ["mpirun", "-np", str(np_cores)] + lmp_cmd
    result = subprocess.run(lmp_cmd, cwd=workdir, capture_output=True, text=True)
    if result.returncode != 0:
        print("  LAMMPS stderr (last 500 chars):")
        print(result.stderr[-500:])
        raise RuntimeError("LAMMPS run failed")

    dump = workdir / "dump_amor.lammpstrj"
    if not dump.exists():
        raise RuntimeError(f"LAMMPS dump not found at {dump}")

    print("  Reading dump and computing RDF ...")
    frames = read_lammps_dump(dump, n_atoms)
    if not frames:
        raise RuntimeError("No frames read from dump file")

    skip_frames = 10
    frames_to_use = frames[skip_frames:] if len(frames) > skip_frames else frames
    print(f"  {len(frames)} frames available; using {len(frames_to_use)} for RDF averaging "
          f"(skipping first {skip_frames})")

    g_total = np.zeros(nbins)
    r = None
    for cell_frame, pos in frames_to_use:
        r, g = compute_rdf(pos, cell_frame, rmax=rmax, nbins=nbins)
        g_total += g
    g_r = g_total / len(frames_to_use)

    i_peak = int(np.argmax(g_r[r < 3.0]))
    r_peak = r[i_peak]

    last_cell, _ = frames_to_use[-1]
    rho = n_atoms / abs(np.linalg.det(last_cell))
    cn = coordination_number(r, g_r, rho, r_cutoff=3.2)

    print(f"  1st peak at r = {r_peak:.3f} Å  [expected ≈ 2.5 Å for a-Ge]")
    print(f"  Coordination number (r < 3.2 Å): {cn:.2f}  [expected ≈ 4 for a-Ge]")

    txt = outdir / "amorphous_rdf.txt"
    with open(txt, "w") as f:
        f.write(f"# Amorphous Ge RDF  |  pot: {pot}\n")
        f.write(f"# T_melt = {T_melt:.0f} K  quench_rate = {quench_rate:.0e} K/s\n")
        f.write(f"# 1st peak at r = {r_peak:.3f} Å   CN = {cn:.2f}\n")
        f.write("# r[A]  g(r)\n")
        for ri, gi in zip(r, g_r):
            f.write(f"  {ri:.4f}  {gi:.6f}\n")
    print(f"  Data written to {txt}")

    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(8, 5))

        # MTP result
        ax.plot(r, g_r, color="tab:purple", lw=1.5, label="MTP")
        ax.axhline(1.0, color="gray", lw=0.8, ls="--")

        # Reference data overlays
        ref_sets = [
            ("Exp. high", "tab:orange", 1.0, ref_highbound),
            ("Exp. low",  "tab:green",  1.0, ref_lowbound),
        ]
        for label, color, alpha, fpath in ref_sets:
            rr, gg = load_ref_rdf(fpath)
            if rr is not None:
                ax.plot(rr, gg, color=color, lw=1.0, ls="--", alpha=alpha, label=label)

        ax.axvline(r_peak, color="tab:red", lw=0.8, ls=":", label=f"1st peak: {r_peak:.2f} Å")
        ax.set_xlabel("r (Å)", fontsize=12)
        ax.set_ylabel("g(r)", fontsize=12)
        ax.set_title(
            f"Amorphous Ge g(r)  [quench {quench_rate:.0e} K/s]", fontsize=13
        )
        ax.legend(fontsize=9)
        ax.set_xlim(0, rmax)
        fig.tight_layout()
        png = outdir / "amorphous_rdf.png"
        fig.savefig(png, dpi=150)
        plt.close(fig)
        print(f"  Plot saved to {png}")
    except ImportError as e:
        print(f"  Matplotlib not available ({e}); skipping plot.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Melt-quench amorphous Ge RDF via LAMMPS"
    )
    parser.add_argument("--pot", required=True, help="Path to potential (.almtp)")
    parser.add_argument("--T-melt", type=float, default=1500.0,
                        help="Melt temperature in K (default: 1500)")
    parser.add_argument("--quench-rate", type=float, default=1e12,
                        help="Quench rate in K/s (default: 1e12; use 1e13 for --quick)")
    parser.add_argument("--quick", action="store_true",
                        help="Use 1e13 K/s quench rate for a quick validation run")
    parser.add_argument("--n-cells", type=int, default=3,
                        help="Supercell repeat (8·n³ atoms, default: 3→216)")
    parser.add_argument("--rmax", type=float, default=8.0)
    parser.add_argument("--nbins", type=int, default=200)
    parser.add_argument("--outdir", default="results/tests/amorphous_rdf")
    parser.add_argument("--lammps", default=LAMMPS_DEFAULT)
    parser.add_argument("--np", type=int, default=1,
                        help="Number of MPI processes (default: 1, wraps with mpirun if >1)")
    parser.add_argument("--ref-highbound", default="src/physical_validation/reference/thermal_properties_EXP/a-Ge_rdf_highbound.dat",
                        help="Reference experimental high-bound RDF .dat file")
    parser.add_argument("--ref-lowbound", default="src/physical_validation/reference/thermal_properties_EXP/a-Ge_rdf_lowbound.dat",
                        help="Reference experimental low-bound RDF .dat file")
    args = parser.parse_args()

    if args.quick and args.quench_rate != 1e12:
        print("  NOTE: --quick overrides --quench-rate; using 1e13 K/s")
    quench_rate = 1e13 if args.quick else args.quench_rate

    run(
        pot=args.pot,
        outdir=Path(args.outdir),
        lammps=args.lammps,
        np_cores=args.np,
        n_cells=args.n_cells,
        T_melt=args.T_melt,
        quench_rate=quench_rate,
        rmax=args.rmax,
        nbins=args.nbins,
        ref_highbound=args.ref_highbound,
        ref_lowbound=args.ref_lowbound,
    )


if __name__ == "__main__":
    main()
