"""Liquid Ge radial distribution function via LAMMPS NVT→NPT→NVT MD.

Three-stage protocol:
  1. NVT pre-heat at the liquid temperature — melt gently at constant volume
  2. NPT equilibration at the liquid temperature / 0 bar — relax to true density
  3. NVT production at the equilibrated density — collect dump frames

Starting from diamond-cubic Ge at the specified lattice constant.
The NPT barostat allows the system to melt and find its natural liquid density.

Two pair styles (--backend):
  lammps-mlip - `pair_style mlip load_from=...` (default), the old
                lammps-stable_23Jun2022_update4-EPH build.
  lammps-nlh  - `pair_style hybrid/overlay mtp nlh` with the new LAMMPS-MTP
                build — needed for potentials trained with a radial basis
                type `pair_style mlip` cannot load ("Wrong radial basis
                type"); see src/physical_validation/elastic_constant/potential.mod for the
                same LAMMPS pair_style workaround used for elastic constants.

Usage:
    python src/physical_validation/liquid_rdf.py --pot results/potentials/pot.almtp
    python src/physical_validation/liquid_rdf.py --pot results/potentials/pot.almtp \\
        --nx 10 --ny 10 --nz 10 --T 1500 --steps-npt 20000 --steps-nvt 10000 \\
        --outdir results/rdf_output
    python src/physical_validation/liquid_rdf.py --pot results/potentials/20.mtp --backend lammps-nlh \\
        --lammps "srun /projappl/project_2012355/CODE/lammps-MTP/src/lmp_mpi"
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "utils"))
from utils import compute_rdf, coordination_number, load_ref_rdf, read_lammps_dump
from energy_volume import DEFAULT_LAMMPS as DEFAULT_LAMMPS_NLH

LAMMPS_DEFAULT = "lmp_mpi"
_GE_MASS_AMU = 72.630
_REF_DIR = Path(__file__).resolve().parent / "reference"

_PAIR_STYLE_BLOCKS = {
    "lammps-mlip": lambda pot_path: (
        f"pair_style  mlip load_from={pot_path}\n"
        f"pair_coeff  * *"
    ),
    "lammps-nlh": lambda pot_path: (
        f"pair_style  hybrid/overlay mtp nlh\n"
        f"pair_coeff  * * mtp {pot_path} 0\n"
        f"pair_coeff  1 1 nlh 32 32 0.05121 0.50355 0.44524 49.82156 12.56998 4.13684 1.28 2.0"
    ),
}

# ---------------------------------------------------------------------------
# LAMMPS input writer
# ---------------------------------------------------------------------------

def write_liquid_input(
    workdir: Path,
    pot_path: str,
    nx: int = 10,
    ny: int = 10,
    nz: int = 10,
    a0: float = 5.5,
    T: float = 2000.0,
    steps_nvt_pre: int = 2_000,
    steps_npt: int = 20_000,
    steps_nvt: int = 2_000,
    seed: int = 12345,
    dump_every: int = 100,
    backend: str = "lammps-nlh",
) -> int:
    """Write LAMMPS input for liquid Ge NPT→NVT MD.

    Returns the number of atoms in the supercell (8 * nx * ny * nz for
    the diamond-cubic conventional cell with 8 atoms).
    """
    n_atoms = 8 * nx * ny * nz
    pair_style_block = _PAIR_STYLE_BLOCKS[backend](pot_path)

    lammps_in = f"""# Liquid Ge NPT→NVT MD — generated by liquid_rdf.py
units       metal
boundary    p p p
atom_style  atomic

# Diamond-cubic supercell: nx={nx} ny={ny} nz={nz}, a0={a0}
lattice     diamond {a0}
region      box block 0 {nx} 0 {ny} 0 {nz} units lattice
create_box  1 box
create_atoms 1 box
mass        1 {_GE_MASS_AMU}

{pair_style_block}

neighbor    2.0 bin
neigh_modify delay 0 every 1 check yes
timestep    0.0005   # ps  (0.5 fs)
thermo      100
thermo_style custom step time temp press vol etotal

# Stage 0: NVT pre-heat at {T:.0f} K — melt gently before barostat
velocity    all create {T} {seed} mom yes rot yes
fix         nvt_heat all nvt temp {T} {T} 0.1
dump        dmp all custom {dump_every} stage0.lammpstrj id type x y z
dump_modify dmp sort id
run         {steps_nvt_pre}
unfix       nvt_heat
undump      dmp

# Stage 1: NPT equilibration at {T:.0f} K, 0 bar
fix         npt_eq all npt temp {T} {T} $(100.0*dt) iso 0.0 0.0 $(1000.0*dt)
dump        dmp all custom {dump_every} stage1.lammpstrj id type x y z
dump_modify dmp sort id
run         {steps_npt}
unfix       npt_eq
undump      dmp    

# Stage 2: NVT production at {T:.0f} K
fix         nvt_prod all nvt temp {T} {T} 0.1
dump        dmp all custom {dump_every} stage2.lammpstrj id type x y z
dump_modify dmp sort id
run         {steps_nvt}
unfix       nvt_prod
undump      dmp

write_data  final.lammps
"""
    tmp = tempfile.NamedTemporaryFile(mode='w', dir='/tmp', delete=False, suffix='.liquid')
    try:
        tmp.write(lammps_in)
    finally:
        tmp.close()
    shutil.move(tmp.name, workdir / "in.liquid")
    return n_atoms

# ---------------------------------------------------------------------------
# RDF from dump (uses shared utils)
# ---------------------------------------------------------------------------

def compute_rdf_from_dump(
    dump_path: Path,
    n_atoms: int,
    rmax: float = 8.0,
    nbins: int = 200,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Read LAMMPS dump, compute and average g(r) over all frames.

    Returns (r, g_r, cells) where cells is an array of per-frame box matrices.
    """
    frames = read_lammps_dump(dump_path, n_atoms)
    if not frames:
        raise RuntimeError(f"No frames read from {dump_path}")

    print(f"  Using {len(frames)} frames for RDF averaging")
    g_total = np.zeros(nbins)
    r = None
    cells = []
    for cell_frame, pos in frames:
        r, g = compute_rdf(pos, cell_frame, rmax=rmax, nbins=nbins)
        g_total += g
        cells.append(cell_frame)

    return r, g_total / len(frames), np.array(cells)

# ---------------------------------------------------------------------------
# Main workflow
# ---------------------------------------------------------------------------

def run(
    pot: str,
    outdir: Path,
    lammps: str,
    nx: int,
    ny: int,
    nz: int,
    a0: float,
    T: float,
    steps_nvt_pre: int,
    steps_npt: int,
    steps_nvt: int,
    rmax: float,
    nbins: int,
    ref_path: str | None = None,
    backend: str = "lammps-mlip",
) -> None:
    """Execute the full liquid RDF workflow.

    Steps:
        1. Write LAMMPS input file
        2. Run LAMMPS MD simulation (NVT pre-heat + NPT equil + NVT production)
        3. Parse dump, compute g(r)
        4. Plot and save RDF figure + data file
    """
    outdir.mkdir(parents=True, exist_ok=True)

    n_atoms = 8 * nx * ny * nz
    total_time_ps = (steps_nvt_pre + steps_npt + steps_nvt) * 0.0005

    print(f"  Liquid Ge at {T:.0f} K  |  {n_atoms} atoms  "
          f"({nx}x{ny}x{nz} diamond cells, a0={a0} A)")
    print(f"  Protocol: {steps_nvt_pre:,} NVT pre-heat + {steps_npt:,} NPT + {steps_nvt:,} NVT steps "
          f"({total_time_ps:.1f} ps total)")

    workdir = outdir / "lammps_run"
    workdir.mkdir(exist_ok=True)

    dump = workdir / "stage2.lammpstrj"
    if dump.exists():
        print(f"  LAMMPS dump is found at {dump}, skip lammps simulation, plot rdf directly")
    else:
        pot_abs = str(Path(pot).resolve())
        dump_every = 100  # per spec: dump every 100 steps during NVT

        n_atoms_written = write_liquid_input(
            workdir, pot_abs,
            nx=nx, ny=ny, nz=nz, a0=a0,
            T=T, steps_nvt_pre=steps_nvt_pre, steps_npt=steps_npt, steps_nvt=steps_nvt,
            dump_every=dump_every, backend=backend,
        )
        assert n_atoms_written == n_atoms

        # Run LAMMPS
        print("  Running LAMMPS ...")
        lmp_cmd = lammps.split() + ["-in", "in.liquid", "-log", "liquid.log"]
        result = subprocess.run(
            lmp_cmd, cwd=workdir, capture_output=True, text=True
        )
        if result.returncode != 0:
            print("  LAMMPS stderr (last 500 chars):")
            print(result.stderr[-500:])
            raise RuntimeError("LAMMPS run failed")

        if not dump.exists():
            raise RuntimeError(f"LAMMPS dump not found at {dump}")

    # Compute RDF
    print("  Computing RDF ...")
    r, g_r, cells = compute_rdf_from_dump(dump, n_atoms, rmax=rmax, nbins=nbins)

    # Density from the actual simulation box (mean over collected frames)
    vols = np.array([abs(np.linalg.det(c)) for c in cells])
    rho = n_atoms / vols.mean()
    density_gcm3 = rho * _GE_MASS_AMU / 0.6022

    cn = coordination_number(r, g_r, rho)
    mask_first = r < 3.5
    if np.any(mask_first):
        i_peak = int(np.argmax(g_r[mask_first]))
        r_peak = r[mask_first][i_peak]
        g_peak = g_r[mask_first][i_peak]
    else:
        i_peak = int(np.argmax(g_r))
        r_peak = r[i_peak]
        g_peak = g_r[i_peak]

    print(f"  1st peak at r = {r_peak:.3f} A,  g(r_peak) = {g_peak:.2f}")
    print(f"  Coordination number (r < 3.5 A): {cn:.2f}  [expected: 6-9]")
    print(f"  Simulation density: {density_gcm3:.3f} g/cm3")

    # Save RDF data
    txt = outdir / "liquid_rdf.txt"
    tmp_txt = tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False, dir="/tmp")
    try:
        tmp_txt.write(f"# Liquid Ge RDF at {T:.0f} K  |  pot: {pot}\n")
        tmp_txt.write(f"# density = {density_gcm3:.3f} g/cm3\n")
        tmp_txt.write(f"# 1st peak at r = {r_peak:.3f} A   CN = {cn:.2f}\n")
        tmp_txt.write("# r[A]  g(r)\n")
        for ri, gi in zip(r, g_r):
            tmp_txt.write(f"  {ri:.4f}  {gi:.6f}\n")
        tmp_txt.close()
        shutil.move(tmp_txt.name, txt)
    finally:
        if not tmp_txt.closed:
            tmp_txt.close()
    print(f"  Data written to {txt}")

    # Plot
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(8, 5))
        ax.plot(r, g_r, color="tab:purple", lw=1.5, label="MTP")
        ax.axhline(1.0, color="gray", lw=0.8, ls="--")

        # Auto-load all rdf_*.dat from the reference/liquid_rdf directory
        _ref_colors = {"dft": "tab:orange", "exp": "tab:green"}
        _ref_label  = {"dft": "DFT", "exp": "Exp."}
        for ref_file in sorted((_REF_DIR / "liquid_rdf").glob("rdf_*.dat")):
            stem = ref_file.stem.replace("rdf_", "").lower()   # e.g. "dft", "exp"
            r_ref, g_ref = load_ref_rdf(str(ref_file))
            if r_ref is not None:
                color = _ref_colors.get(stem, "tab:gray")
                label = _ref_label.get(stem, stem)
                ax.plot(r_ref, g_ref, color=color, lw=1.0, ls="--",
                        alpha=0.9, label=label)

        # Overlay additional user-specified reference if provided
        r_ref, g_ref = load_ref_rdf(ref_path)
        if r_ref is not None:
            ax.plot(r_ref, g_ref, color="tab:red", lw=1.0, ls=":",
                    alpha=0.9, label="ref")

        ax.axvline(r_peak, color="tab:red", lw=0.8, ls=":",
                   label=f"1st peak: {r_peak:.2f} A")
        ax.set_xlabel("r (A)", fontsize=12)
        ax.set_ylabel("g(r)", fontsize=12)
        backend_tag = "" if backend == "lammps-mlip" else " (mtp+nlh)"
        ax.set_title(
            f"Liquid Ge g(r) at {T:.0f} K{backend_tag}  "
            f"[p = {density_gcm3:.2f} g/cm3]",
            fontsize=13,
        )
        ax.legend(fontsize=10)
        ax.set_xlim(0, rmax)
        fig.tight_layout()
        png = outdir / "liquid_rdf.png"
        tmp_png = tempfile.NamedTemporaryFile(suffix=".png", delete=False, dir="/tmp")
        tmp_png.close()
        fig.savefig(tmp_png.name, dpi=150)
        shutil.move(tmp_png.name, png)
        plt.close(fig)
        print(f"  Plot saved to {png}")
    except ImportError as e:
        print(f"  Matplotlib not available ({e}); skipping plot.")

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Liquid Ge RDF test via LAMMPS NPT->NVT MD"
    )
    parser.add_argument(
        "--pot", required=True,
        help="Path to MTP potential file (.almtp)"
    )
    parser.add_argument(
        "--nx", type=int, default=10,
        help="Number of unit cells in x direction (default: 10)"
    )
    parser.add_argument(
        "--ny", type=int, default=10,
        help="Number of unit cells in y direction (default: 10)"
    )
    parser.add_argument(
        "--nz", type=int, default=10,
        help="Number of unit cells in z direction (default: 10)"
    )
    parser.add_argument(
        "--a0", type=float, default=5.76,
        help="Lattice constant for diamond-cubic Ge in A (default: 5.76)"
    )
    parser.add_argument(
        "--T", type=float, default=2000.0,
        help="Liquid temperature in K (default: 2000)"
    )
    parser.add_argument(
        "--steps-nvt-pre", type=int, default=2_000,
        help="NVT pre-heat steps before NPT (default: 1 ps)"
    )
    parser.add_argument(
        "--steps-npt", type=int, default=20000,
        help="NPT equilibration steps (default: 10 ps)"
    )
    parser.add_argument(
        "--steps-nvt", type=int, default=2_000,
        help="NVT production steps (default: 1 ps)"
    )
    parser.add_argument(
        "--backend", choices=["lammps-mlip", "lammps-nlh"], default="lammps-mlip",
        help="'lammps-mlip' (default): pair_style mlip. 'lammps-nlh': pair_style "
             "hybrid/overlay mtp nlh — for potentials 'lammps-mlip' can't load."
    )
    parser.add_argument(
        "--lammps", default=None,
        help="LAMMPS binary path (default: lmp_mpi for --backend lammps-mlip, "
             f"{DEFAULT_LAMMPS_NLH} for --backend lammps-nlh)"
    )
    parser.add_argument(
        "--outdir", default=None,
        help="Output directory (default: results/tests/<pot's parent dir "
             "name>/liquid_rdf, e.g. --pot results/potentials/pot_660277/pot.almtp "
             "-> results/tests/pot_660277/liquid_rdf)"
    )
    parser.add_argument(
        "--rmax", type=float, default=8.0,
        help="Max r for g(r) in A (default: 8.0)"
    )
    parser.add_argument(
        "--nbins", type=int, default=200,
        help="Number of RDF bins (default: 200)"
    )
    parser.add_argument(
        "--ref", default=None,
        help="Optional path to reference RDF data file for overlay"
    )
    args = parser.parse_args()

    lammps = args.lammps
    if lammps is None:
        lammps = LAMMPS_DEFAULT if args.backend == "lammps-mlip" else DEFAULT_LAMMPS_NLH

    if args.outdir is None:
        run_name = Path(args.pot).resolve().parent.name
        outdir = Path("results/tests") / run_name / "liquid_rdf"
    else:
        outdir = Path(args.outdir)

    run(
        pot=args.pot,
        outdir=outdir,
        lammps=lammps,
        nx=args.nx,
        ny=args.ny,
        nz=args.nz,
        a0=args.a0,
        T=args.T,
        steps_nvt_pre=args.steps_nvt_pre,
        steps_npt=args.steps_npt,
        steps_nvt=args.steps_nvt,
        rmax=args.rmax,
        nbins=args.nbins,
        ref_path=args.ref,
        backend=args.backend,
    )

if __name__ == "__main__":
    main()
